/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class htools_core_input_Jwintab */

#ifndef _Included_htools_core_input_Jwintab
#define _Included_htools_core_input_Jwintab
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     htools_core_input_Jwintab
 * Method:    getVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_htools_core_input_Jwintab_getVersion
  (JNIEnv *, jclass);

/*
 * Class:     htools_core_input_Jwintab
 * Method:    open
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_htools_core_input_Jwintab_open
  (JNIEnv *, jclass, jstring);

/*
 * Class:     htools_core_input_Jwintab
 * Method:    close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_htools_core_input_Jwintab_close
  (JNIEnv *, jclass);

/*
 * Class:     htools_core_input_Jwintab
 * Method:    getPacket
 * Signature: ([F[F[I[J)I
 */
JNIEXPORT jint JNICALL Java_htools_core_input_Jwintab_getPacket
  (JNIEnv *, jclass, jfloatArray, jfloatArray, jintArray, jlongArray);

#ifdef __cplusplus
}
#endif
#endif
