/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ParametersFrame.java
 *
 * Created on 2 avr. 2010, 12:32:27
 */

package hollerbachsynthetiser;

import java.awt.event.ActionListener;
import javax.swing.event.ChangeListener;

/**
 *
 * @author rvlander
 */
public class ParametersFrame extends javax.swing.JFrame implements NextObserver {

    /** Creates new form ParametersFrame */
    public ParametersFrame() {
        initComponents();
    }

    public void addStateChangedListenerToSliders(ChangeListener listener){
        aSlider.addChangeListener(listener);
        bSlider.addChangeListener(listener);
        phixSlider.addChangeListener(listener);
        phiySlider.addChangeListener(listener);
        wxSlider.addChangeListener(listener);
        wySlider.addChangeListener(listener);
    }

    public void addSaveLoadButtonListener(ActionListener al){
        this.saveButton.addActionListener(al);
        this.loadButton.addActionListener(al);
        this.clearButton.addActionListener(al);
    }

    public void addPlayListener(ActionListener al){
        this.playButton.addActionListener(al);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aLabel = new javax.swing.JLabel();
        bLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        aSlider = new javax.swing.JSlider();
        bSlider = new javax.swing.JSlider();
        phixSlider = new javax.swing.JSlider();
        phixLabel = new javax.swing.JLabel();
        phiySlider = new javax.swing.JSlider();
        phiyLabel = new javax.swing.JLabel();
        wxSlider = new javax.swing.JSlider();
        wxLabel = new javax.swing.JLabel();
        wySlider = new javax.swing.JSlider();
        wyLabel = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        loadButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        j0phi = new javax.swing.JLabel();
        playButton = new javax.swing.JButton();
        jPR = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        aLabel.setText("a");
        aLabel.setName("a"); // NOI18N

        bLabel.setText("b");
        bLabel.setName("b"); // NOI18N

        aSlider.setName("a"); // NOI18N

        bSlider.setName("b"); // NOI18N

        phixSlider.setName("phix"); // NOI18N

        phixLabel.setText("phix");
        phixLabel.setName("phix"); // NOI18N

        phiySlider.setName("phiy"); // NOI18N

        phiyLabel.setText("phiy");
        phiyLabel.setName("phiy"); // NOI18N

        wxSlider.setName("wx"); // NOI18N

        wxLabel.setText("wx");
        wxLabel.setName("wx"); // NOI18N

        wySlider.setName("wy"); // NOI18N

        wyLabel.setText("wy");
        wyLabel.setName("wy"); // NOI18N

        saveButton.setText("Save");
        saveButton.setName("saveButton"); // NOI18N

        loadButton.setText("Load");
        loadButton.setName("loadButton"); // NOI18N

        clearButton.setText("Clear");
        clearButton.setName("clearButton"); // NOI18N

        j0phi.setText("c-asin(phi)");
        j0phi.setName("c-asin(phi)"); // NOI18N

        playButton.setText("Play !");

        jPR.setText("PR");
        jPR.setName("PR"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(aLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 306, Short.MAX_VALUE)
                        .addComponent(aSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 306, Short.MAX_VALUE)
                        .addComponent(bSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(phixLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 292, Short.MAX_VALUE)
                        .addComponent(phixSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(phiyLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 292, Short.MAX_VALUE)
                        .addComponent(phiySlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(wxLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 298, Short.MAX_VALUE)
                        .addComponent(wxSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(wyLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 298, Short.MAX_VALUE)
                        .addComponent(wySlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(saveButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loadButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 272, Short.MAX_VALUE)
                        .addComponent(playButton))
                    .addComponent(j0phi)
                    .addComponent(jPR))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(aSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bSlider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(phixSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phixLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(phiySlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phiyLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(wxSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wxLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(wySlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wyLabel))
                .addGap(18, 18, 18)
                .addComponent(j0phi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(loadButton)
                    .addComponent(clearButton)
                    .addComponent(playButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
  /*  public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ParametersFrame().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aLabel;
    private javax.swing.JSlider aSlider;
    private javax.swing.JLabel bLabel;
    private javax.swing.JSlider bSlider;
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel j0phi;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jPR;
    private javax.swing.JButton loadButton;
    private javax.swing.JLabel phixLabel;
    private javax.swing.JSlider phixSlider;
    private javax.swing.JLabel phiyLabel;
    private javax.swing.JSlider phiySlider;
    private javax.swing.JButton playButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel wxLabel;
    private javax.swing.JSlider wxSlider;
    private javax.swing.JLabel wyLabel;
    private javax.swing.JSlider wySlider;
    // End of variables declaration//GEN-END:variables

    public void updated(ParametersHollerbach ph) {
        this.aLabel.setText(this.aLabel.getName() + " " + ph.a);
        this.bLabel.setText(this.bLabel.getName() + " " + ph.b);
        this.phixLabel.setText(this.phixLabel.getName() + " " + ph.phix*180/Math.PI+"°");
        this.phiyLabel.setText(this.phiyLabel.getName() + " " + ph.phiy*180/Math.PI+"°");
        this.wxLabel.setText(this.wxLabel.getName() + " " + ph.wx);
        this.wyLabel.setText(this.wyLabel.getName() + " " + ph.wy);
        this.j0phi.setText(this.j0phi.getName() +" --- " + (ph.c-ph.a*Math.sin(ph.phix-ph.phiy)));
        double degangle = (ph.phix-ph.phiy)*180/Math.PI;
        this.jPR.setText(this.jPR.getName() +" --- " + degangle);

        this.aSlider.setValue((int)WritingPanel.uscale(ph.a, 0, 200));
        this.bSlider.setValue((int)WritingPanel.uscale(ph.b, 0, 200));
        this.phixSlider.setValue((int)WritingPanel.uscale(ph.phix, 0, 2*Math.PI));
        this.phiySlider.setValue((int)WritingPanel.uscale(ph.phiy, 0, 2*Math.PI));
        this.wxSlider.setValue((int)WritingPanel.uscale(ph.wx, -20,20));
        this.wySlider.setValue((int)WritingPanel.uscale(ph.wy, -20,20));

        
    }

    public void next(int deactive) {
     /*   System.out.println(deactive);

        if (deactive==0){
            this.aSlider.setEnabled(true);
            this.bSlider.setEnabled(true);
            this.phixSlider.setEnabled(true);
            this.phiySlider.setEnabled(true);
            this.wxSlider.setEnabled(true);
            this.wySlider.setEnabled(true);
        }
        else if(deactive==1){
            this.aSlider.setEnabled(true);
            this.bSlider.setEnabled(false);
            this.phixSlider.setEnabled(true);
            this.phiySlider.setEnabled(false);
            this.wxSlider.setEnabled(true);
            this.wySlider.setEnabled(false);
        }else if (deactive == 2){
            this.aSlider.setEnabled(false);
            this.bSlider.setEnabled(true);
            this.phixSlider.setEnabled(false);
            this.phiySlider.setEnabled(true);
            this.wxSlider.setEnabled(false);
            this.wySlider.setEnabled(true);
        }*/
    }

}
